version: "1.0"
stages:
  - "clone"
  - "build"
  - "deploy"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    stage: "clone"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "jagzwohlig/transport-api"
    tag: "${{CF_BRANCH}}-${{CF_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
    registry: "dockerhub"
  deploy:
    title: Running Deploy Script
    type: deploy
    kind: kubernetes
    cluster: "digitalOcean@transports-project"
    namespace: "dev"
    service: transport-api
    candidate:
      image: "${{build}}"
      registry: "dockerhub"
    stage: "deploy"
